--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/PocketMineItalianDevs/TapToArmor
build-by-default: true
branches:
- master
projects:
  TapToArmor:
    icon: "icon.png"
    path: ""
...
